### ISSUE TITLE
bundler: failed to load command: shoryuken

### ISSUE THREAD

**Issue by bismark64** [joekhoobyar/capistrano-shoryuken#2]
First of all, thanks for this gem! 
I'm getting an error when running capistrano:

``` bash
bundler: failed to load command: shoryuken (..../bundle/ruby/2.2.0/bin/shoryuken)
SignalException: SIGHUP
  ..../bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies/autoload.rb:26:in `<module:Autoload>'
  ..../bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies/autoload.rb:25:in `<module:ActiveSupport>'
  ..../bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies/autoload.rb:3:in `<top (required)>'
  ..../bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support.rb:25:in `require'
  ..../bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support.rb:25:in `<top (required)>'
  ..../bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails.rb:5:in `require'
  ..../bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails.rb:5:in `<top (required)>'
  ..../bundle/ruby/2.2.0/gems/shoryuken-2.0.11/lib/shoryuken/environment_loader.rb:85:in `require'
  ..../bundle/ruby/2.2.0/gems/shoryuken-2.0.11/lib/shoryuken/environment_loader.rb:85:in `load_rails'
  ..../bundle/ruby/2.2.0/gems/shoryuken-2.0.11/lib/shoryuken/environment_loader.rb:18:in `load'
  ..../bundle/ruby/2.2.0/gems/shoryuken-2.0.11/lib/shoryuken/environment_loader.rb:6:in `load'
  ..../bundle/ruby/2.2.0/gems/shoryuken-2.0.11/lib/shoryuken/cli.rb:37:in `run'
  ..../bundle/ruby/2.2.0/gems/shoryuken-2.0.11/bin/shoryuken:6:in `<top (required)>'
  ..../bundle/ruby/2.2.0/bin/shoryuken:23:in `load'
  ..../bundle/ruby/2.2.0/bin/shoryuken:23:in `<top (required)>'
```

This is only happening when using `--daemon`, without it it works.
What am I missing?

**Comment by johnmcauley** [comment]
I have the exact same problem.

**Comment by johnmcauley** [comment]
bundler: failed to load command: shoryuken (/home/alkimiideploy/shared/bundle/ruby/2.3.0/bin/shoryuken)
SignalException: SIGQUIT
  /home/alkimiideploy/shared/bundle/ruby/2.3.0/gems/shoryuken-2.0.11/lib/shoryuken/cli.rb:54:in `select'
  /home/alkimiideploy/shared/bundle/ruby/2.3.0/gems/shoryuken-2.0.11/lib/shoryuken/cli.rb:54:in `run'
  /home/alkimiideploy/shared/bundle/ruby/2.3.0/gems/shoryuken-2.0.11/bin/shoryuken:6:in `<top (required)>'
  /home/alkimiideploy/shared/bundle/ruby/2.3.0/bin/shoryuken:23:in `load'
  /home/alkimiideploy/shared/bundle/ruby/2.3.0/bin/shoryuken:23:in `<top (required)>'
2017-01-23T14:41:49Z 5559 TID-1gi7eo ERROR:

**Comment by marzhaev** [comment]
It would fail for me too if I launch it via capistrano as a part of Rails deployment.

It works though if SSH in mainly launch: 
RAILS_ENV=production bundle exec shoryuken --daemon --pidfile 'path_to_pid_file' --logfile 'path_to_log_file' --config 'path_to_config_file' --queue tescrawlers --rails -c 5

**Comment by manhdaovan** [comment]
@bismark64 Pls check your options `:pty` in your deploy file. Set it to `false` if it is being `true`, then try again.
I guess the process has been terminated before command completed.
Ref: https://github.com/rbenv/rbenv/wiki/Unix-shell-initialization
